[kind.colon]
token = ":"
is = ['infix-op']

[kind.dot]
token = "."
is = ['infix-op']

[kind.question-mark]
token = "?"
is = ['postfix-op']

[kind.exclamation-mark]
token = "!"
is = ['prefix-op']

[kind.equals]
token = "="
is = ['infix-op']

[kind.greater-than]
token = ">"
is = ['infix-op']

[kind.less-than]
token = "<"
is = ['infix-op']

[kind.plus]
token = "+"
is = ['infix-op', 'prefix-op']

[kind.minus]
token = "-"
is = ['infix-op', 'prefix-op']

[kind.star]
token = "*"

[kind.percent]
token = "%"

[kind.caret]
token = "^"

[kind.tilde]
token = "~"

[kind.slash]
token = "/"
is = ['infix-op']

[kind.pipe]
token = "|"
is = ['infix-op']

[kind.at]
token = "@"

[kind.hash]
token = "#"

[kind.ampersand]
token = "&"

[kind.semicolon]
token = ";"

[kind.comma]
token = ","

[kind.l-brace]
token = "{"
shortcut = "'}'"

[kind.r-brace]
token = "}"
shortcut = "'{'"

[kind.l-paren]
token = "("
shortcut = "'('"

[kind.r-paren]
token = ")"
shortcut = "')'"

[kind.l-bracket]
token = "["
shortcut = "'['"

[kind.r-bracket]
token = "]"
shortcut = "']'"

# Non reference identifiers are the same as identfiers but allow `_` instead of `-`,
# this is because otherwise we wouldn't be able to distinguish between substraction and
# such. This would otherwise make whitespace significant, which we would like to avoid.
#
# An implementation should search for a token sequence of `ident` `-` `ident` `-` `ident`
# with no trailing `-` for the `reference-ident`.
[kind.ident]
regex = ["[_a-zA-Z][a-zA-Z0-9_]*"]

[kind.string]
regex = [
    '"(?:[^\\"]|\\.)*"',
    '''(?x)
        '(?:[^\\']|\\.)*'
    '''
]
is = ['literal']

[kind.integer]
regex = ["[+-]?(([1-9][0-9]*)|0)"]
is = ['literal']

[kind.number]
regex = ["[+-]?(([1-9][0-9]*)|0)\\.[0-9]+"]
priority = 16
is = ['literal']

[kind.true-kw]
token = "true"
is = ['literal']

[kind.false-kw]
token = "false"
is = ['literal']

[kind.null-kw]
token = "null"
is = ['literal']

#--------Reserved--------#
[kind.let-kw]
token = "let"

[kind.fn-kw]
token = "fn"

[kind.loop-kw]
token = "loop"

[kind.match-kw]
token = "match"

[kind.for-kw]
token = "for"

[kind.if-kw]
token = "if"

[kind.else-kw]
token = "else"

[kind.return-kw]
token = "return"

[kind.continue-kw]
token = "continue"

[kind.break-kw]
token = "break"

[kind.while-kw]
token = "while"

[kind.try-kw]
token = "try"

[kind.static-kw]
token = "static"

[kind.move-kw]
token = "move"

[kind.async-kw]
token = "async"
#------------------------#

[kind.whitespace]
regex = ["\\s"]
is = ['trivia']

[kind.comment]
regex = ["//.*"]
is = ['trivia']

[syntax.data-item]
[syntax.prop-item]
[syntax.link-item]
[syntax.entity-item]
[syntax.use-item]
[syntax.set-item]

# TODO: this still uses `=`
[syntax.alias-item]
[syntax.alias-data-item]
[syntax.alias-prop-item]
[syntax.alias-link-item]
[syntax.alias-entity-item]

[syntax.record-expr]
[syntax.record-expr-entry]
[syntax.literal]
[syntax.map-expr]
[syntax.list-expr]
[syntax.paren-expr]
[syntax.infix-expr]
[syntax.prefix-expr]
[syntax.postfix-expr]
[syntax.tuple-expr]
[syntax.range-expr]

# TODO: use `:` for types instead of the stmt level
[syntax.union-type]
[syntax.record-type]
[syntax.record-type-entry]
[syntax.list-type]
[syntax.map-type]
[syntax.tuple-type]

[syntax.path]
[syntax.path-segment]

# this is special, because a string might be prefixed and suffixed by an identifier
[syntax.literal-string]
[syntax.literal-string-prefix]
[syntax.literal-string-suffix]

# This identifier is only used for references, other variables use the `_`,
# otherwise arithmatic would be impossible.
[syntax.reference-ref]
[syntax.name]
[syntax.name-ref]

[syntax.comment-doc]

[syntax.attribute]
[syntax.meta]
[syntax.token-tree]

# TODO: function expression and such
[syntax.call-expr]
[syntax.call-args]

# These are compound syntax kinds, which are supposed to be joined together
[syntax.colon2]
shortcut = "::"
composite = [':', ':']
[syntax.pipe2]
shortcut = "||"
composite = ['|', '|']
[syntax.gt2]
shortcut = ">>"
composite = ['>', '>']
[syntax.gt-eq]
shortcut = ">="
composite = ['>', '=']
[syntax.lt2]
shortcut = "<<"
composite = ['<', '<']
[syntax.lt-eq]
shortcut = "<="
composite = ['<', '=']
[syntax.eq2]
shortcut = "=="
composite = ['=', '=']
[syntax.star2]
shortcut = "**"
composite = ['*', '*']
[syntax.ampersand2]
shortcut = "&&"
composite = ['&', '&']
[syntax.dot2]
shortcut = ".."
composite = ['.', '.']
[syntax.dot2-eq]
shortcut = "..="
composite = ['.', '.', '=']
[syntax.minus-gt]
shortcut = "->"
composite = ['-', '>']
[syntax.tilde-gt]
shortcut = "~>"
composite = ['~', '>']
[syntax.lt-minus]
shortcut = "<-"
composite = ['<', '-']
[syntax.lt-tilde]
shortcut = "<~"
composite = ['<', '~']

[syntax.data-kw]
contextual = "data"
[syntax.prop-kw]
contextual = "prop"
[syntax.link-kw]
contextual = "link"
[syntax.entity-kw]
contextual = "entity"
[syntax.alias-kw]
contextual = "alias"
[syntax.use-kw]
contextual = "use"
[syntax.set-kw]
contextual = "set"

#----------------------------#
#       Precedence Table     #
#----------------------------#
[[precedence]]
infix-left = ["="]

[[precedence]]
infix-left = ["..=", ".."]

# Combinators
[[precedence]]
infix-left = ["||"]

[[precedence]]
infix-left = ["&&"]

[[precedence]]
prefix = ["!"]

# Comparisons
[[precedence]]
infix-left = ["==", "<=", ">=", "<", ">"]

# Binary Operations
[[precedence]]
infix-left = [">>", "<<"]

[[precedence]]
infix-left = ["^"]

[[precedence]]
infix-left = ["&"]

[[precedence]]
infix-left = ["|"]

# Arithmatic Operations
[[precedence]]
infix-left = ["+", "-"]

[[precedence]]
infix-left = ["*", "/", "%"]

[[precedence]]
infix-right = ["**"]

[[precedence]]
prefix = ["+", "-"]

# (for now unused)
[[precedence]]
postfix = ["?"]