[kind.colon]
literal = ":"

[kind.dot]
literal = "."

[kind.question-mark]
literal = "?"

[kind.equals]
literal = "="

[kind.greater-than]
literal = ">"

[kind.less-than]
literal = "<"

[kind.plus]
literal = "+"

[kind.minus]
literal = "-"

[kind.star]
literal = "*"

[kind.slash]
literal = "/"

[kind.pipe]
literal = "|"

[kind.at]
literal = "@"

[kind.hash]
literal = "#"

[kind.ampersand]
literal = "&"

[kind.semicolon]
literal = ";"

[kind.comma]
literal = ","

[kind.lbrace]
literal = "{"

[kind.rbrace]
literal = "}"

[kind.lparen]
literal = "("

[kind.rparen]
literal = ")"

[kind.lbracket]
literal = "["

[kind.rbracket]
literal = "]"

[kind.ident]
regex = ["[a-zA-Z][a-zA-Z0-9-]*"]

[kind.string]
regex = ['"(?:[^\\"]|\\.)*"', "'(?:[^\\\\']|\\.)*'"]

[kind.integer]
regex = ["[+-]?(([1-9][0-9]*)|0)"]

[kind.number]
regex = ["[+-]?(([1-9][0-9]*)|0)\\.[0-9]+"]
priority = 12

[kind.kw-true]
literal = "true"

[kind.kw-false]
literal = "false"

[kind.whitespace]
regex = ["\\s"]

[kind.comment]
regex = ["//.*"]

[syntax.data-stmt]
[syntax.prop-stmt]
[syntax.link-stmt]
[syntax.entity-stmt]
[syntax.let-stmt]
[syntax.use-stmt]
[syntax.set-stmt] # TODO: consider removing this (only used for configuration?!)

# TODO: this still uses `=`
[syntax.alias-data-stmt]
[syntax.alias-prop-stmt]
[syntax.alias-link-stmt]
[syntax.alias-entity-stmt]

[syntax.record-expr]
[syntax.record-expr-entry]
[syntax.literal-expr]
# this is special, because a string might be prefixed and suffixed by an identifier
[syntax.string-expr]
[syntax.map-expr]
[syntax.list-expr]
[syntax.module-expr]
[syntax.paren-expr]
[syntax.infix-expr]
[syntax.prefix-expr]
[syntax.postfix-expr]
[syntax.tuple-expr]
[syntax.range-expr]

# TODO: use `:` for types instead of the stmt level
[syntax.union-type]
[syntax.record-type]
[syntax.record-type-entry]
[syntax.list-type]
[syntax.map-type]
[syntax.tuple-type]

[syntax.reference]
[syntax.variable]

[syntax.comment-doc]
[syntax.attribute]

# TODO: function expression and such
[syntax.call-expr]
[syntax.call-args]
