[kind.colon]
literal = ":"

[kind.question-mark]
literal = "?"

[kind.equals]
literal = "="

[kind.greater-than]
literal = ">"

[kind.less-than]
literal = "<"

[kind.plus]
literal = "+"

[kind.minus]
literal = "-"

[kind.star]
literal = "*"

[kind.slash]
literal = "/"

[kind.pipe]
literal = "|"

[kind.at]
literal = "@"

[kind.hash]
literal = "#"

[kind.ampersand]
literal = "&"

[kind.semicolon]
literal = ";"

[kind.comma]
literal = ","

[kind.lbrace]
literal = "{"

[kind.rbrace]
literal = "}"

[kind.lparen]
literal = "("

[kind.rparen]
literal = ")"

[kind.lbracket]
literal = "["

[kind.rbracket]
literal = "]"

[kind.ident]
regex = ["[a-zA-Z][a-zA-Z0-9-]*"]

[kind.string]
regex = ['"(?:[^\\"]|\\.)*"', "'(?:[^\\\\']|\\.)*'"]

[kind.integer]
regex = ["[+-]?(([1-9][0-9]*)|0)"]

[kind.number]
regex = ["[+-]?(([1-9][0-9]*)|0)\\.[0-9]+"]
priority = 12

[kind.kw-true]
literal = "true"

[kind.kw-false]
literal = "false"

[kind.whitespace]
regex = ["\\s"]

[kind.comment]
regex = ["//.*"]