[package]
name = "syntax"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rowan = "0.15.8"

num-derive = "0.3.3"
num-traits = "0.2.15"

lexer = { path = "../lexer" }